server:
  port: 8080
  servlet:
    context-path: /cadastro_pessoa

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/BD_PESSOAS
    username: postgres
    password: "0000"
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none